// ── UPGRADE SCREEN ────────────────────────────────────────
// Full screen upgrade page
// Shown when user taps upgrade from paywall

export default function UpgradeScreen({ onBack }) {
  const plans = [
      {
            id: 'monthly',
                  label: 'Monthly',
                        price: 'Choose your price',
                              period: 'per month',
                                    badge: null
                                        },
                                            {
                                                  id: 'annual',
                                                        label: 'Annual',
                                                              price: 'Best value',
                                                                    period: 'per year',
                                                                          badge: 'SAVE 40%'
                                                                              }
                                                                                ]

                                                                                  const features = [
                                                                                      { icon: '📊', text: 'Unlimited sheets' },
                                                                                          { icon: '♾️', text: 'Unlimited rows per sheet' },
                                                                                              { icon: '📥', text: 'Import CSV files' },
                                                                                                  { icon: '📤', text: 'Export to Excel (.xlsx)' },
                                                                                                      { icon: '🔄', text: 'Sync across all devices' },
                                                                                                          { icon: '🧮', text: 'Advanced formulas' },
                                                                                                              { icon: '⚡', text: 'Priority support' },
                                                                                                                  { icon: '🔒', text: 'Your data encrypted' },
                                                                                                                    ]

                                                                                                                      return (
                                                                                                                          <div className="min-h-screen bg-gray-950 text-white flex flex-col">

                                                                                                                                {/* Header */}
                                                                                                                                      <div className="bg-gray-900 border-b border-gray-800 px-4 py-4 flex items-center gap-3">
                                                                                                                                              <button
                                                                                                                                                        onClick={onBack}
                                                                                                                                                                  className="text-gray-400 text-2xl w-10 h-10 flex items-center justify-center"
                                                                                                                                                                          >←</button>
                                                                                                                                                                                  <h1 className="text-white font-bold text-base">Upgrade to Pro</h1>
                                                                                                                                                                                        </div>

                                                                                                                                                                                              <div className="flex-1 overflow-y-auto px-4 py-6 space-y-6">

                                                                                                                                                                                                      {/* Hero */}
                                                                                                                                                                                                              <div className="text-center space-y-2">
                                                                                                                                                                                                                        <div className="text-5xl">⬡</div>
                                                                                                                                                                                                                                  <h2 className="text-2xl font-bold text-white">Onyx Pro</h2>
                                                                                                                                                                                                                                            <p className="text-gray-400 text-sm">
                                                                                                                                                                                                                                                        Everything you need to work faster on mobile
                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                  {/* Features */}
                                                                                                                                                                                                                                                                                          <div className="bg-gray-900 rounded-2xl p-5 space-y-4">
                                                                                                                                                                                                                                                                                                    {features.map((f, i) => (
                                                                                                                                                                                                                                                                                                                <div key={i} className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                              <span className="text-xl">{f.icon}</span>
                                                                                                                                                                                                                                                                                                                                            <span className="text-gray-200 text-sm flex-1">{f.text}</span>
                                                                                                                                                                                                                                                                                                                                                          <span className="text-green-400">✓</span>
                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                {/* Plans */}
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-400 text-xs text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                              Pricing coming soon — join the waitlist to get early access pricing
                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {plans.map(plan => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={plan.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="bg-gray-900 border border-gray-700 rounded-2xl p-4 flex items-center justify-between"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-white font-semibold">{plan.label}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {plan.badge && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="bg-green-900 text-green-300 text-xs px-2 py-0.5 rounded-full font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {plan.badge}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-500 text-xs mt-0.5">{plan.period}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-indigo-400 text-sm font-semibold">{plan.price}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* CTA */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.open('mailto:hello@mewt.space?subject=Onyx Pro Early Access', '_blank')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full bg-indigo-600 text-white font-bold py-4 rounded-xl text-base active:bg-indigo-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Join Early Access Waitlist
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-600 text-xs text-center pb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        No payment required. We'll notify you when Pro launches.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }