// Cell.jsx — Memoized cell component with local edit state
// Editing state lives here, never in the parent GridScreen

import { useState, useRef, memo } from 'react'
import { getDisplayValue, isFormula } from '../utils/formulas'

const Cell = memo(function Cell({ row, col, rows, columns, onSave, isDark }) {
  const [isEditing, setIsEditing] = useState(false)
    const [localValue, setLocalValue] = useState('')
      const inputRef = useRef(null)

        const rawValue = row.cells?.[col.id] || ''
          const displayValue = getDisplayValue(rawValue, rows, columns)

            const text = isDark ? 'text-white' : 'text-gray-900'
              const cellBorder = isDark ? 'border-gray-900' : 'border-gray-200'

                // Decide input type once at focus time — never changes mid-edit
                  // This prevents keyboard thrashing on mobile
                    const inputType = useRef('text')

                      function handleOpen() {
                          // Lock in the input type before focusing — do not change after
                              if (!rawValue.startsWith('=') && col.type === 'date') {
                                    inputType.current = 'date'
                                        } else if (col.type === 'number') {
                                              inputType.current = 'text' // text so formula = works
                                                  } else {
                                                        inputType.current = 'text'
                                                            }
                                                                setLocalValue(rawValue)
                                                                    setIsEditing(true)
                                                                        setTimeout(() => {
                                                                              inputRef.current?.focus()
                                                                                    if (inputType.current === 'date') {
                                                                                            inputRef.current?.showPicker?.()
                                                                                                  }
                                                                                                      }, 0)
                                                                                                        }

                                                                                                          function handleSave() {
                                                                                                              setIsEditing(false)
                                                                                                                  // Only bubble up if value actually changed
                                                                                                                      if (localValue !== rawValue) {
                                                                                                                            onSave(row.id, col.id, localValue)
                                                                                                                                }
                                                                                                                                  }

                                                                                                                                    function handleKeyDown(e) {
                                                                                                                                        if (e.key === 'Enter') handleSave()
                                                                                                                                            if (e.key === 'Escape') {
                                                                                                                                                  setLocalValue(rawValue)
                                                                                                                                                        setIsEditing(false)
                                                                                                                                                            }
                                                                                                                                                              }

                                                                                                                                                                return (
                                                                                                                                                                    <td
                                                                                                                                                                          className={`border-l ${cellBorder} p-0`}
                                                                                                                                                                                style={{ minWidth: '140px' }}
                                                                                                                                                                                    >
                                                                                                                                                                                          {isEditing ? (
                                                                                                                                                                                                  <input
                                                                                                                                                                                                            ref={inputRef}
                                                                                                                                                                                                                      type={inputType.current}
                                                                                                                                                                                                                                inputMode={
                                                                                                                                                                                                                                            localValue.startsWith('=')
                                                                                                                                                                                                                                                          ? 'text'
                                                                                                                                                                                                                                                                        : col.type === 'number'
                                                                                                                                                                                                                                                                                      ? 'decimal'
                                                                                                                                                                                                                                                                                                    : 'text'
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                        value={localValue}
                                                                                                                                                                                                                                                                                                                                  onChange={e => setLocalValue(e.target.value)}
                                                                                                                                                                                                                                                                                                                                            onBlur={handleSave}
                                                                                                                                                                                                                                                                                                                                                      onKeyDown={handleKeyDown}
                                                                                                                                                                                                                                                                                                                                                                className="w-full h-full bg-indigo-950 text-white px-4 py-4 text-sm outline-none border-2 border-indigo-500"
                                                                                                                                                                                                                                                                                                                                                                          style={{ minWidth: '140px' }}
                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                          onPointerDown={handleOpen}
                                                                                                                                                                                                                                                                                                                                                                                                                    className={`px-4 py-4 text-sm min-h-14 select-none
                                                                                                                                                                                                                                                                                                                                                                                                                                active:bg-indigo-950
                                                                                                                                                                                                                                                                                                                                                                                                                                            ${isFormula(rawValue) ? 'text-indigo-400' : text}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ minWidth: '140px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {displayValue || (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className={`${isDark ? 'text-gray-700' : 'text-gray-300'} text-xs`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tap to edit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default Cell
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            