// ── PAYWALL ───────────────────────────────────────────────
// Shown when user hits a free tier limit
// Prompts upgrade to Pro

import BottomSheet from './BottomSheet'

export default function Paywall({ message, onClose, onUpgrade }) {
  return (
      <BottomSheet title="Upgrade to Pro" onClose={onClose}>
            <div className="space-y-6">

                    {/* Message */}
                            <div className="bg-indigo-950 border border-indigo-800 rounded-2xl p-4">
                                      <p className="text-indigo-200 text-sm text-center leading-relaxed">
                                                  {message}
                                                            </p>
                                                                    </div>

                                                                            {/* Pro features list */}
                                                                                    <div className="space-y-3">
                                                                                              {[
                                                                                                          { icon: '📊', text: 'Unlimited sheets' },
                                                                                                                      { icon: '♾️', text: 'Unlimited rows per sheet' },
                                                                                                                                  { icon: '📥', text: 'Import CSV files' },
                                                                                                                                              { icon: '📤', text: 'Export to Excel' },
                                                                                                                                                          { icon: '🔄', text: 'Sync across all your devices' },
                                                                                                                                                                      { icon: '🧮', text: 'Advanced formulas' },
                                                                                                                                                                                ].map((feature, i) => (
                                                                                                                                                                                            <div key={i} className="flex items-center gap-3">
                                                                                                                                                                                                          <span className="text-xl">{feature.icon}</span>
                                                                                                                                                                                                                        <span className="text-gray-300 text-sm">{feature.text}</span>
                                                                                                                                                                                                                                      <span className="ml-auto text-green-400 text-sm">✓</span>
                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                            {/* Pricing hint */}
                                                                                                                                                                                                                                                                                    <div className="text-center">
                                                                                                                                                                                                                                                                                              <p className="text-gray-500 text-xs">
                                                                                                                                                                                                                                                                                                          Monthly and annual plans available
                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                    {/* CTA buttons */}
                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                      onClick={onUpgrade}
                                                                                                                                                                                                                                                                                                                                                                className="w-full bg-indigo-600 text-white font-bold py-4 rounded-xl text-base active:bg-indigo-700"
                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                  Upgrade to Pro →
                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                            onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full text-gray-500 text-sm py-2"
                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                        Maybe later
                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </BottomSheet>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }